version: '3.9'

x-base_service: &base_service
  volumes:
    - &v_data ./data:/data
    - &v_model ./models:/models
  environment:
    TZ: Asia/Seoul
  stop_signal: SIGKILL
  tty: true

name: riiid-p3

services:

  train:
    <<: *base_service
    profiles: [ "train" ]
    build:
      context: ./train
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_model
      - *v_data
      - ./train:/workspace/ # DEV
    command: /bin/bash # DEV

  serve:
    <<: *base_service
    ports:
      - "${DEV_PORT:-18080}:8080"
    profiles: [ "serve" ]
    environment:
      MODEL_PATH: /models/model.pkl
    build:
      context: ./serve
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_model

      - *v_data # DEV
      - ./serve:/api # DEV
    command: /bin/bash # DEV
