version: '3.9'

x-base_service: &base_service

  volumes:
    - &v_data ./P3:/data
  environment:
    TZ: Asia/Seoul
  stop_signal: SIGKILL
  tty: true

name: riiid-p3

services:
  
  # ----- BACKEND ----- #
  prod:
    <<: *base_service
    ports:
      - "${PROD_PORT:-8080}:8080"
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - *v_prod

  dev:
    <<: *base_service
    ports:
      - "${DEV_PORT:-8081}:8080"
    profiles: ["dev"]
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_dev
      - *v_src
    command: /bin/bash
