version: '3.9'

x-base_service:

  &base_service
  volumes:
    - &v_data ./data:/data
    - &v_model ./models:/models
  environment:
    TZ: Asia/Seoul
  stop_signal: SIGKILL
  tty: true

name: riiid-p3

services:

  train:
    <<: *base_service
    profiles: [ "train" ]
    build:
      context: ./train
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_data
      - *v_model
      - ./train:/workspace/
    command: /bin/bash

  serve:
    <<: *base_service
    ports:
      - "${DEV_PORT:-18080}:8080"
    profiles: [ "serve" ]
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - *v_data
      - .:/api
    command: /bin/bash
